- name: Copy mongodb to yum.repo.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo
  
- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Start & Enable MongoDB Service
  ansible.builtin.service:
  name: mongod
    state: started
    enabled: yes

- name: Enable remote connection to mongod
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart mongod
  ansible.builtin.service:
    name: mongod
    state: restarted